### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by wuliwux** [koltyakov/generator-sppp#10]
Hi, 
greet Project!
Upload works fine, but i have this error...

![unbenannt](https://user-images.githubusercontent.com/1975703/32903392-2ea70ca6-caf5-11e7-8fce-6ab817cbfaa3.PNG)

node: v8.9.0
npm: 5.5.1

and the default generated code.

greets

**Comment by koltyakov** [comment]
Hi @wuliwux,

Thanks for reporting this!
I'll take a look into.

**Comment by koltyakov** [comment]
Hey @wuliwux,

Could you please update sp-build-tasks library to v1.4.5?
It should update its dependency which is in charge of live reaload - sp-live-reload, where the issue was located and fixed. Please make sure that the version of sp-live-reload is 2.0.10.

**Comment by wuliwux** [comment]
perfekt this problem solved!

**Comment by koltyakov** [comment]
Nice! Closing the issues.
