### ISSUE TITLE
npm run config

### ISSUE THREAD

**Issue by MercerK** [koltyakov/generator-sppp#12]
Ran "yo sppp".
At the conclusion, it said "run `npm run config` to configure SharePoint connection".
When running the command, got "missing script error".

When reviewing the wiki, I found the command to be "gulp config".

**Comment by MercerK** [comment]
My bad. I think it happened as I ran "npm init" first and it didn't update package.json with the scripts when running "yo sppp". When creating a new project and only running the "yo sppp" command follow by the "npm run config", it worked fine.

**Comment by koltyakov** [comment]
Yeah, I do not rewrite existing files for safety, just log out skip messages.
Could be not quite obvious in the case of npm initiation before running the generator.
Glad you figured it out and thank you for the interest! Closing the issue as answered.
