### ISSUE TITLE
custom task are not working when created in the ./buils/tasks as per Documentations.

### ISSUE THREAD

**Issue by JCol79** [koltyakov/generator-sppp#18]
...looking at the ./gulpfile.js line 26. It looks as 'sp-build-tasks' is being configured to look taskPath: './tools/tasks' instead './build/tasks',

generated ./gulpfile.js warns against modifying this file directly so I created .\tools\tasks\example.js and ran 'gulp example' to test as well as 'gulp --tasks' and it worked.

**Comment by koltyakov** [comment]
Thanks, @JCol79! Published a fix.
