### ISSUE TITLE
no site url?

### ISSUE THREAD

**Issue by andyr00d** [koltyakov/generator-sppp#20]
Hello,

I'm not seeing the "Site URL" and other options as per your images when creating a new application via the CLI... am I missing something?

![image](https://user-images.githubusercontent.com/16533699/49630068-806b8a00-fa27-11e8-93fb-4eecc4eaac9a.png)

**Comment by koltyakov** [comment]
Hi @andyr00d,

SharePoint connection wizard is now separate from generator's.
To connect to SharePoint run `npm run config`.

**Comment by andyr00d** [comment]
Ah got it, thank you!
