### ISSUE TITLE
 spsave: Error occured when running gulp push

### ISSUE THREAD

**Issue by thisisspeedy** [koltyakov/generator-sppp#21]
> [[90m13:12:40[39m] Starting 'push'...
> 
> [33m===[39m [32mPublishing assets to SharePoint[39m [33m===[39m
> 
> [31m[13:12:42] spsave: Error occured:[39m
> [31m[13:12:42] spsave: 403 - "{\"error\":{\"code\":\"-2147024891, System.UnauthorizedAccessException\",\"message\":{\"lang\":\"en-US\",\"value\":\"Access denied. You do not have permission to perform this action or access this resource.\"}}}"[39m
> 
I'm a site collection admin. What can be causing this?

**Comment by koltyakov** [comment]
Is it SharePoint Online, Modern site? With custom scripts disabled even an admin can't perform scripts upload.

**Comment by thisisspeedy** [comment]
Even after running? 
`Set-SPOSite -Identity https://tenant.sharepoint.com/sites/contoso -DenyAddAndCustomizePages 0
`
