### ISSUE TITLE
multi-factor authentication

### ISSUE THREAD

**Issue by sitipoi** [koltyakov/generator-sppp#24]
I am using SPO and I can't seem to login because we are using multi-factor authentication

**Comment by koltyakov** [comment]
Hi @sitipoi,

With 2FA it's possible authenticating using:
- [On-Demand](https://github.com/s-KaiNet/node-sp-auth/wiki/On-demand-authentication) authentication 
- [Add-In Only](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint-Online-addin-only-authentication) permissions
- Creating [App Password](https://github.com/s-KaiNet/gulp-spsave/issues/31#issuecomment-360161754)

**Comment by sitipoi** [comment]
when I use `gulp pull` it asks me for the 

- SharePoint URL : https://*****.sharepoint.com/sites/thisismysite
- Authentication strategy: User credentials (SAML/ADFS)
- Username: *****
- Password: ****
`Folders proceeding: 0 out of 0 [recursive scanning...]
Error in getFolderContent: <S:Fault>
  <S:Code>
    <S:Value>S:Sender</S:Value>
    <S:Subcode>
      <S:Value>wst:FailedAuthentication</S:Value>
    </S:Subcode>
  </S:Code>
  <S:Reason>
    <S:Text xml:lang="en-US">Authentication Failure</S:Text>
  </S:Reason>
  <S:Detail>
  </S:Reason>
  <S:Detail>
    <psf:error xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault">
    <psf:error xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault">
      <psf:value>0x800434D4</psf:value>
      <psf:internalerror>
        <psf:code>0x800434D4</psf:code>
        <psf:text>AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access &apos;&apos;.</psf:text>
      </psf:internalerror>
    </psf:error>
  </S:Detail>
</S:Fault>`

so can I just create an app password (generated thru our 2fa site) and use that password? this is the same in my other office applications when logging in.
