### ISSUE TITLE
Publish to SP fails if there's a mandatory field to be set

### ISSUE THREAD

**Issue by kunalkankariya** [koltyakov/generator-sppp#29]
While pushing files to SP (publish), if my masterpage library has a mandatory Title column then the push fails. Where do I make changes to handle such issues without making Title optional in SP.

Also, where are the gulp tasks, I don't see them in the gulpfile.js.

Thanks!

**Comment by koltyakov** [comment]
This feature initially was not implemented, yet supported in spsave.
Added the layer for setting up spsave filesMetadata. You got to update to sp-build-tasks@3.9.1.
Then, restart VSCode and modify `./config/app.json` file:

```json
{
  //...
  "filesMetaData": [
    {
      "fileName": "my-master-page.aspx",
      "metadata": {
        "__metadata": {
          "type": "SP.Data.OData__x005f_catalogs_x002f_masterpageItem"
        },
        "Title": "Custom title"
      }
    }
  ]}
```

Thought, modifying `/_catalogs/masterpages` library is a bad, really bad practice. And you'll have to provide metadata for each and every asset file you have in the solution. This scenario is not supported, only via custom upload task.

**Comment by kunalkankariya** [comment]
Thank you so much @koltyakov !!!

I was trying this out on a test site and there Title was mandatory. I know that this isn't the case for our production sites. I was wondering if it was possible.  :)

Thanks again!

**Comment by koltyakov** [comment]
Great!
