### ISSUE TITLE
Dev proxy and other webs

### ISSUE THREAD

**Issue by clechner77** [koltyakov/generator-sppp#36]
Getting access denied when I try to use a web other than the one setup in the project connection.

Example, project setup to root https://xxx.sharepoint.com

Then I add a new context via...
```
import { Web } from "@pnp/sp/webs";
const web = Web("https://something.sharepoint.com/sites/dev");
const items = await web.lists.getByTitle('MyList').items.get();

```
Access denied.  Haven't looked at the underlying setup yet to dig in yet.

**Comment by koltyakov** [comment]
Hi Clint,

In a local workbench, a request sent to an external resource is obviously being sent to an external resource but not via any magic through a proxy. 

In a default config, starting `npm run start` the `sp-rest-proxy` server is initiated in Webpack Dev Server, which hosts local assets and API calls routes through the proxy.

Let's assume `npm run start` is by default has started at `http://localhost:9090` and that [local context helper](https://github.com/koltyakov/sp-rest-proxy#load-page-context-helper) (which is also configured as a sample in SPPP) is used, and proxy is configured to talk to `https://xxx.sharepoint.com/sites/dev01`. When, `_spPageContextInfo` variable is initiated, close to the one on a real classic SharePoint page. Default PnPjs's `sp.web` object uses `_spPageContextInfo.webAbsoluteUrl` (along other ways of web binding) to build web object like `Web(_spPageContextInfo.webAbsoluteUrl)`. In case of proxy,  `_spPageContextInfo.webAbsoluteUrl` would be `http://localhost:9090/sites/dev01`, but not the one at `xxx.sharepoint.com` host. So the request is sent to the proxy via Webpack Dev Server and then to the real SP site with the addition of auth headers, etc.

That's how it works.

So, if you need another web, different from that configured in sp-rest-proxy config file, you need to use its relative path with a local hostname and port:

```typescript
const web = Web('http://localhost:9090/sites/dev02');

// of course, `http://localhost:9090` should not be hardcoded but constructed based
// on `window.location.href.indexOf('://localhost') === -1` logic to work the same in local
// and SharePoint hosted modes

const items = await web.lists.getByTitle('MyList').items.get();
console.log({ items });
```

**Comment by clechner77** [comment]
Hah, that was one of those questions where after you get the answer you feel silly asking the original question.  Makes complete sense now.  Thank you for the detailed answer as well.
