### ISSUE TITLE
Request for SPPP deployment thru Azure Dev Ops sample

### ISSUE THREAD

**Issue by alexleely** [koltyakov/generator-sppp#38]
Hi Koltyakov,

I would like to seek your help in adding a sample for Azure Dev OPS deployment for SPPP. Also is it possible to deploy to mulitple sites at once because private.json only capture 1 sites?
Thank you so much

Best Regards
Alex Lee

**Comment by koltyakov** [comment]
Hi @alexleely, thanks for posting the sample request.
Please check out the [sample for configuring CI/CD](https://github.com/koltyakov/sppp-cicd-sample).
Please let me know if you have any questions.

**Comment by alexleely** [comment]
Hi @koltyakov , thanks so much for the quick response. This is very helpful!!
