### ISSUE TITLE
live-reload merging

### ISSUE THREAD

**Issue by vladivanovrf** [koltyakov/generator-sppp#6]
Hello
I think, it will be better to merge "gulp live-reload-install" with "gulp watch-live". So, when you start live-reload watching, it automatically deploys custom action to SharePoint. And when you stop, it automatically retracts custom action.

**Comment by koltyakov** [comment]
Hi Vlad,

It's not ideologically correct to install a custom action when running watch-live task as there are so many cases when having custom action installed is not desired. For example, there are 2 or more developers working on separate modules on the same site and agreed to use manual, per module, live-reload script provisioning in the CEWP's body.

But you can easily combine and reuse existing gulp tasks by adding something like this:

```javascript
gulp.task("install-and-watch-live", ['live-reload-install', 'watch-live']);
```

**Comment by vladivanovrf** [comment]
Of course there must be alternatives

> gulp.task("install-and-watch-live", ['live-reload-install', 'watch-live']);
Yes, something like this should be by default, because it is one of the most often cases. It will be better to input in console and keep in mind just one command. And it will be great (if possible) to make automatical retract after stopping "install-and-watch-live" task, because forget to retract is normal :)

**Comment by koltyakov** [comment]
Custom tasks now can be easily added to `./build/tasks` folder.
Please check an examle.js, also you can get the available tasks with `gulp --tasks` and combine some of them together if you need.
