### ISSUE TITLE
Unable to Pull Sharepoint Online & Sharepoint 2016 folders

### ISSUE THREAD

**Issue by mcowley5** [koltyakov/generator-sppp#7]
Hi,

I've got a local instance of SharePoint 2016 running and an SharePoint Online developer account, which I can't seem to get it to work with either installation. 

I've tried using gulp sppull-all and I get the "Finished" message, however it does say processing 0 out of 0 folders.

![image](https://cloud.githubusercontent.com/assets/25504990/22548762/f6c12f02-e93f-11e6-9718-4c1aec507ba4.png)

Am I missing something for this behaviour?

**Comment by koltyakov** [comment]
Hi,

Are you using default generated app.config.json?
Is there a `spRootFolder` property targeting SharePoint folder?

By default it's `_catalogs/masterpage/spf` which can easily be empty in your environments.
SPPull has a number of modes, in sppp it uses root folder, requests and downloads folders and files recursively. If a target folder is empty '0 out of 0' is expected.

So, please check the `spRootFolder` parameter and the place there you are going to publish asset files.

**Comment by mcowley5** [comment]
Thank you - I had chosen the defaults and my `spRootFolder `was empty and pointing to `_catalogs/masterpage/spf.`

User error - Thanks for replying

**Comment by koltyakov** [comment]
You are welcome
