### ISSUE TITLE
Investigate a way of adding Angular to sppp's projects

### ISSUE THREAD

**Issue by koltyakov** [koltyakov/generator-sppp#9]
- Readme with some recommendations
- or sub generator

**Comment by Brainstem** [comment]
I installed generator-sppp, then tried to install ng new {dir}, but met with errors:

error! SpppAng4/package.json already exists.
error! SpppAng4/tsconfig.json already exists.
error! SpppAng4/tslint.json already exists.
error! SpppAng4/.gitignore already exists.

Still investigating.

**Comment by koltyakov** [comment]
`ng` tries creating these files of its own and fails as they already exist.

My plan/vision here is:
- check what Angular CLI do when creating a new project
- add a script which would add Angular dependencies
- configuration for webpack
- patching gulp or npm tasks with Angular specific

**Comment by koltyakov** [comment]
Some thoughts so far:

- It's not a good idea to do not use Angular CLI or reproduce its actions in sppp
- Angular CLI presumably doesn't support initiation in existing node.js project (`ng init` is deprecated)
- Angular app can be created inside sppp project in a child folder with `ng new [app_name]`
- Angular output folder can be redefined in `.angular-cli.json` with something like `../dist/[app_name]` so angular build files can be placed into the folder where sppp's watches changes to upload to SharePoint or in opposite sppp's dist folder path can be redefined
- `ng serve` stores files in memory without dumping changes on disk, so `ng serve` is a cool way of developing with `sp-rest-proxy`, but without instant files upload to SharePoint
- `ng build --watch` can be used for monitoring changes in Angular app's files and dumping output folder with instant files upload
- `ng build --watch` in Angular app's folder can be used together with `gulp watch` or `gulp live` in sppp's project folder
- [concurrently](https://www.npmjs.com/package/concurrently) module can be helpful in running two or more tasks at the same time

At the same time, sppp's library which is in charge of build automation - [sp-build-tasks](https://www.npmjs.com/package/sp-build-tasks) - can be added to any existing Angular project with some manual actions, adding `config` (connection to SharePoint), `watch`, `live` and `push` tasks to a project.

**Comment by Brainstem** [comment]
|   ...sppp's library ... can be added to any existing Angular project...

I created an angular app from the start and now I want to get sppp's library integrated to perform automatic TC compiles, bundles in .dist, and pushes to SharePoint.  Can you outline the steps for this integration or changes to the generator-sppp?  I'm still new to yoeman and gulp so I'm afraid I don't know what to change.

**Comment by koltyakov** [comment]
Saying this I did not mean that [sp-build-tasks](https://github.com/koltyakov/sp-build-tasks) should be installed with sppp generator. `sp-build-tasks` is a heart of sppp's automation, but in the same time a standalone library.

Well we can try the following:

1\. New Angular app

```bash
ng new myApp
cd myApp
```

2\. Install SharePoint build tasks and Concurrently

```bash
npm install sp-build-tasks concurrently --save-dev
```

3\. Create `./config/app.json` with content:

```json
{
  "$schema": "../node_modules/sp-build-tasks/schema/v1/sppp.json",
  "spFolder": "_catalogs/masterpage/myApp",
  "distFolder": "./dist"
}
```

4\. Copy [gulpfile.js](https://github.com/koltyakov/generator-sppp/blob/master/src/templates/gulpfile.js) into project's root

5\. Add following npm task into package.json to scripts section:

```json
...
"scripts": {
  ...
  "spdev": "concurrently --kill-others \"ng build --watch\" \"gulp watch\""
  ...
}
...
```

6\. Config SharePoint connection by running:

```bash
gulp config
```

This should be done only once.

7\. Run new watch task:

```bash
npm run spdev
```

8\. Happy coding!

**Comment by koltyakov** [comment]
I'm close to creating a subgenerator which could sppp'fy any node.js project or Angular in particular by doing 2-5 automatically.

**Comment by koltyakov** [comment]
@Brainstem forget about previously described manual steps, I’ll publish new version of generator Angular-aware when installing to existing Angular app. Testing the changes before publish.

**Comment by Brainstem** [comment]
No problem.  Thanks for your dedication and help.

**Comment by koltyakov** [comment]
Some updates:

Ng app should be built with `-d` parameter with publishing path:

```bash
ng build -w -d https://contoso.sharepoint.com/sites/site/_catalogs/masterpage/publishing_path
```

so when the app's html link is placed as a content link for CEWP Angular app will work.

I still have some open questions (to myself in general, about the way how to deal with Angular solutions with combination with SharePoint in an optimal way) and I can't publish sppp's update without understanding how to solve them. Please bear with me. 

Also, I'm ending up with the idea that local Angular development is more convenient using rest proxy with OOTB ng serve options. And then having Angular-specific tasks which will do following actions:
- Run test [optionally]
- Build Angular dist with `prod`, `aot` and `d` flags, etc.
- Delete published Angular solution's folder/files in SharePoint
- Upload dist folder's content to SharePoint
