### ISSUE TITLE
File not found using sp.web.getFolderByServerRelativeUrl(folder).files.add(`test.rtf`, templateData, true);

### ISSUE THREAD

**Issue by Gennady-G** [koltyakov/generator-sppp#93]
Hi Andrew!

Used You example from [here](https://github.com/pnp/pnpjs/issues/196#issuecomment-410784443) to upload file from template (SP2019 on-prem version)

```
 (async () => {
      const templateUrl = "/sites/Quality/SQE/Shared Documents/qdr_tempate_en.rtf";
      const folder = "/sites/Quality/SQE/QDR_Reports";

      sp.web
        .getFileByServerRelativeUrl(templateUrl)
        .getBuffer()
        .then((templateData) => {
          console.log("template data:");
          console.log(templateData);
          // return sp.web.getFolderByServerRelativeUrl(folder).files.add(`${new Date()}.rtf`, templateData, true); 
          return sp.web.getFolderByServerRelativeUrl(folder).files.add(`test.rtf`, templateData, true); // <-- Fails here
        })
        .then(({ file }) => {
          return file.getItem();
        })
        .then((item) => {
          return item.validateUpdateListItem(
            [
              // Doesn't not create new version
              { FieldName: "Title", FieldValue: `Generated ${new Date()}` },
            ],
            true
          );
        })
        .then(console.log);
    })().catch(console.log);
```

Strange that it is working if I run it in PnPjs Console (from [SPEditor](https://chrome.google.com/webstore/detail/sp-editor/ecblfcmjnbbgaojblcpmjoamegpbodhd) chrome extension):

![err-0-2023-09-09_181624](https://github.com/koltyakov/generator-sppp/assets/5569346/6762c504-c18c-4f96-8ba0-b8c9178a0c64)

But it gives error in sppp generator

![err1-2023-09-09_174259](https://github.com/koltyakov/generator-sppp/assets/5569346/0743a47b-9c74-41ab-9050-915934fae0e3)

Also if I use (new Date) in filename it shows different error, and the url contains subweb only(I have site-collection and a child web http://sppp/sites/Quality/SQE/ , it shows subweb only, not all server-relative path..):

![err2-2023-09-09_174454](https://github.com/koltyakov/generator-sppp/assets/5569346/628877cb-ba35-460f-b323-3f61cbaaf2aa)

Also I am using old v16.20.2 nodejs version (newest gave errors with sppp). Am I doing something wrong, or maybe it is something related with https://github.com/pnp/pnpjs/issues/196 or https://github.com/koltyakov/sp-rest-proxy/issues/61 ?

**Comment by koltyakov** [comment]
When you use `sp.web.getFolderByServerRelativeUrl(folder)` it's important that `web` was within the context of right site. In your case a sub site `/sites/Quality/SQE`.

Otherwise SQE will be treated as a document library on `/sites/Quality`.

It's always better not using `sp.web` but `const web = new Web(siteUri)` or const web = `Web(siteUri)` depending on PnPjs version.

Also, when it comes to proxying request the site context can be involved. Yet, it will usually work if you provide a root site (`/sites/Quality`) for queries to the sub sites.

**Comment by Gennady-G** [comment]
Greetings Andrew!

Thank you much for the clarification! 
Strange that if I set server-relative path to subsite like this `const web = new Web("/sites/Quality/SQE");` - it doubles path in query:
![double-2023-09-11_152415](https://github.com/koltyakov/generator-sppp/assets/5569346/50ac5ae7-46dd-40c3-a837-5beba716227a)

Finally it worked like this: `const web = new Web("SQE");` (this code is strange but it works):

```
      const templateUrl = "/sites/Quality/SQE/Shared Documents/qdr_tempate_en.rtf";
      const folder = "/sites/Quality/SQE/QDR_Reports";

      const web = new Web("SQE");  /* <----- only subweb here */
      console.log(web);

      web
        .getFileByServerRelativeUrl(templateUrl)
        .getBuffer()
        .then((templateData) => {
          return web.getFolderByServerRelativeUrl(folder).files.add("test2.rtf", templateData, true);
        })
        .then(({ file }) => {
          return file.getItem();
        })
        .then((item) => {
          return item.validateUpdateListItem(
            [
              // Doesn't not create new version
              { FieldName: "Title", FieldValue: `Generated ${new Date()}` },
            ],
            true
          );
        })
        .then(console.log);
```

update: or even slash only, if I leave sp.web:

```
const templateUrl = "/sites/Quality/SQE/Shared Documents/qdr_tempate_en.rtf";
      const folder = "/sites/Quality/SQE/QDR_Reports";

      sp.web
        .getFileByServerRelativeUrl(templateUrl)
        .getBuffer()
        .then((templateData) => {

          const subweb = new Web("/");  // <-------
          return subweb.getFolderByServerRelativeUrl(folder).files.add("test5.rtf", templateData, true);
        })
        .then(({ file }) => {
          return file.getItem();
        })
        .then((item) => {

          (async () => {
            const createdFileData: any = await item.select("File/ServerRelativeUrl").expand("File").get();
            const createdFileUrl = await createdFileData.File.ServerRelativeUrl;

          })().catch(console.log);

          return item.validateUpdateListItem(
            [
              // Doesn't not create new version
              { FieldName: "Title", FieldValue: `Generated ${new Date()}` },
            ],
            true
          );
        })
        .then(console.log);
```

**Comment by koltyakov** [comment]
Sorry for confusion, it should have been an absolute path in `new Web`.

**Comment by Gennady-G** [comment]
> Sorry for confusion, it should have been an absolute path in `new Web`.

In this case I get CORS error..
```
      const web = new Web("https://sppp/sites/Quality/SQE/");

      web
        .getFileByServerRelativeUrl(templateUrl)
        //...

```
![3cors-2023-09-12_154543](https://github.com/koltyakov/generator-sppp/assets/5569346/970431ed-6b79-49f9-b2c5-b1a12602de99)

I added self-signed certificate to my dev 2019 and used `httpS://` in path , but with same result.
So unfortunately cannot test with absolute path..
But previous code works for me in SPPP and in pnpjs console also, thank You!

**Comment by koltyakov** [comment]
@Gennady-G then you work with proxy, surely, you make sure that the absolute path is the local one which reaches dev server -> proxy but not SharePoint site directly.

**Comment by Gennady-G** [comment]
Argh! :)

Wow..
Yes I have two computers: dev server and a virtual machine with sp2019

So I need to point to http://**localhost:9090/sites**/..?

Replaced sp.web with Web constructor and now it works:
```
      const templateUrl = "/sites/Quality/SQE/Shared Documents/qdr_tempate_en.rtf";
      const folder = "/sites/Quality/SQE/QDR_Reports";
      
      const web = new Web("http://localhost:9090/sites/Quality/SQE/");
```

 thank You much again Andrew! :)
