### ISSUE TITLE
How to deploy to prod correctly?

### ISSUE THREAD

**Issue by Gennady-G** [koltyakov/generator-sppp#94]
Hi Andrew!

Again not an issue but a question.. Can You please help me how to deploy final solution to prod?
I created small app using my local on-prem, then I change SPWeb url from 

> http://localhost:9090/sites/site/web

 to production url:

![prod-2023-10-11_190212](https://github.com/koltyakov/generator-sppp/assets/5569346/8bced095-e5b7-440d-959b-0397c506b56f)

Then I do 

> npm run connect

 to my prod site, 

> npm run publish

the I add Wiki page, insert classic CEWP there and link it to my-app.cewp.html

> sockjs.js GET https://localhost:9090/sockjs-node/info?t=

![sock-2023-10-11_190346](https://github.com/koltyakov/generator-sppp/assets/5569346/7799a12c-079e-42e1-99da-4a5a89870c11)

![rd-2023-10-11_191000](https://github.com/koltyakov/generator-sppp/assets/5569346/1744a091-0ca7-4873-a47b-24f79fc63b9f)

My code works but these multiple errors appear too. Do I need to change some other setting or I am doing something wrong?..

**Comment by Gennady-G** [comment]
Also can see this string in bundled app.js:

![wp-2023-10-11_211104](https://github.com/koltyakov/generator-sppp/assets/5569346/fe210989-304b-4dd2-be7d-fa8b7b6a2d0b)

**Comment by koltyakov** [comment]
Hi @Gennady-G,

There is nothing special with the deployment. But one should never hardcode the URL, it's always relative and dynamic, based on the place it's run.

Same source code runs in a local workbench and production. You use context `_spPageContextInfo.webAbsoluteUrl` for the legacy SharePoint pages. See: https://github.com/koltyakov/sp-rest-proxy#load-page-context-helper.

When running a build and deploy commands, the relative path is build to host JS/CSS/cewp.html in site assets folder.

**Comment by koltyakov** [comment]
Also, in CEWP you should have `{{ publishPath }}`:

<img width="887" alt="image" src="https://github.com/koltyakov/generator-sppp/assets/7816483/7fb0c931-deb1-4d36-9e29-bfe84d421372">

If changed to something else, it won't be updated when bundling.

**Comment by Gennady-G** [comment]
Hi Andrew!
I haven't touched the publishPath..

Interesting - tried to recreate new test project from scratch (the only difference - I used spf**2** folder)

![1-2023-10-11_225445](https://github.com/koltyakov/generator-sppp/assets/5569346/71b25b20-a5e3-4143-b7c3-d39c0f56ed92)

Tried Your code with no hard-coded urls:

```
import { sp, Web } from "@pnp/sp";
import { loadPageContext } from "sp-rest-proxy/dist/utils/env";

import { loadContext } from "@utils/env";
import { logger } from "@utils/logger";
import { setupPnp } from "@utils/odata";

loadContext()
  .then(() => {
    setupPnp();

    const container = document.getElementById("example-cewp-container");

    if (container) {
      loadPageContext()
        .then(async () => {
          const web = new Web(_spPageContextInfo.webAbsoluteUrl);
          console.log(_spPageContextInfo);

          // test load items
          (async () => {
            
            const items = await web.lists.getByTitle("My list").items.select("Id", "FileLeafRef").filter("Id gt 7800").orderBy("Id", false).getAll();
            console.log(`Got ${items.length} items here`);

          })().catch((err) => {
            console.log(err);
          });
        })
        .catch(console.warn);
    }
  })
  .catch(logger.error);

```

> npm run connect
> npm run start
> npm run publish

and this behaviour repeats. It works Ok but tries to relate with localhost:9090:

![err-1-2023-10-11_231640](https://github.com/koltyakov/generator-sppp/assets/5569346/f87011fe-09e8-436d-a291-dc24a8ba73f9)
![err-2-2023-10-11_231719](https://github.com/koltyakov/generator-sppp/assets/5569346/41c64c6e-e2ec-4d80-87e5-16075f4107b1)
![err-3-2023-10-11_232307](https://github.com/koltyakov/generator-sppp/assets/5569346/7c9be98d-283a-4a6e-8efd-d0cdb213dc02)

Am I right that this error is only "the noise" and does not affect final solution?

**Comment by koltyakov** [comment]
There should be no such error.

Just loaded a blank new created starter project:

```bash
npx -p yo -p generator-sppp -c 'yo sppp'
npm run connect
npm run build
npm run publish
```

<img width="584" alt="image" src="https://github.com/koltyakov/generator-sppp/assets/7816483/00ac44c0-c0f6-4446-abc7-923e38587fdb">

No messages in console with the exception of those produced by SharePoint.

UPD:

You're using `npm run start`, but it should be `npm run build`.

**Comment by Gennady-G** [comment]
> You're using npm run start, but it should be npm run build.

Yes, You are right! Sorry for stupid questions) Thank You Andrew as usual! :-D
